### ISSUE TITLE
Custom Element Menu is buggy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [umlet/umlet#141]
```
Edit selected menu item is not enabled when it should be enabled (everytime the 
custom element panel is not visible and a custom element is selected)
```

Original issue reported on code.google.com by `AFDiaX` on 22 Jun 2013 at 9:36

**Comment by mickours** [comment]
In UMLet 14.1.1 the *Custom Elements > Edit Selected...* is always disabled.

Is it a regression of this bug?

**Comment by afdia** [comment]
It works on my PC.
Are we talking about the UMLet standalone version or the Eclipse plugin?
Does the context menu "Edit Selected" work?

**Comment by mickours** [comment]
I am using the standalone version on Linux and I get the same behaviour with both java version:
```
java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (Arch Linux build 7.u95_2.6.4-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
java -version
openjdk version "1.8.0_74"
OpenJDK Runtime Environment (build 1.8.0_74-b02)
OpenJDK 64-Bit Server VM (build 25.74-b02, mixed mode)

```

The context menu that I get with the right click on an element, do not contain an "Edit Selected" entry.

**Comment by afdia** [comment]
It does so only for Custom Elements:
![editselected](https://cloud.githubusercontent.com/assets/8770707/13839445/5ea1bb78-ec1b-11e5-85d9-4b7720a8fda4.png)

Edit Selected from the menu is also gray for normal elements and only enabled for custom elements (which must be created by "Custom Element -> New..." before)

**Comment by mickours** [comment]
Ok, I understand now, thanks!

It would be great to have the possibility to edit other elements, is it a feature that is in the roadmap?

Maybe you should add some line in the doc about this because if it wasn't clear for my it should also for others.

Thanks anyway :)

**Comment by afdia** [comment]
No problem, in fact since v14 we also offer a slightly less powerful but safer way to customize elements, even existing ones (although currently there exist a bug that the rightmost and bottommost pixel is not visible on exported uxfs for some elements and customizations - see #356 and #353)

I have also written a short summary about old vs new custom elements, because I agree with you that this is not obvious to users:
https://github.com/umlet/umlet/wiki/Common-Problems#what-is-the-difference-between-custom-elements-and-the-elements-in-the-custom-drawings-palette

Please let me know if anything is unclear or not well described.
