### ISSUE TITLE
Formatting of "indented" items

### ISSUE THREAD

**Issue by laughlinbarker** [umlet/umlet#249]
I sometimes indent (four spaces, because tab doesn't seem to work) text in an element. But seems that text formatting doesn't work once it's been "indented" (see attached). Umlet 13.2, Win7 x86, Java 1.6

![umlet_formatting_bug](https://cloud.githubusercontent.com/assets/3249523/6907533/d480755a-d6eb-11e4-9091-22ef99949cf5.PNG)

**Comment by afdia** [comment]
Formatting also works with spaces, but you must place the * at the start of the line. Eg:
*      mytext*
will work

The reason is that formatting characters must always be placed at the beginning and end of a line (even if it starts with spaces)
Perhaps we will support single word formatting in the future (see issue #2) but at the moment this seems to be working as intended
