### ISSUE TITLE
Difficulty changing arrows in large class diagrams.

### ISSUE THREAD

**Issue by kpdowns** [umlet/umlet#260]
When working with large diagrams and attempting to place arrows between classes, it is close to impossible to grab anchor points without creating a new point. Every time an anchor point is clicked and dragged, a new point on the line is created. Takes multiple attempts in order to even move an arrow on the diagram because of this.

Java version: 8u40 (build 1.8.0_40-b26)
Umlet version: 13.2
OS: Windows 8.1 and Ubuntu Linux

**Comment by afdia** [comment]
Hi
Do you mean the selection radius of 10px (on 100% zoom) for relation endpoints is too small? Are we talking about 100% zoom or lower values?

I agree that on lower zoom levels (< 50%), it's quite hard to click inside of the circle to move an endpoint instead of clicking on the line to create a new relation-point. Perhaps we could increase the relation-end-drag-circle for lower zoom levels.

**Comment by kpdowns** [comment]
Hi
Not necessarily too small. It is easy to click inside of the circles for the anchor points, but those clicks don't always register, and sometimes when they do a new point on the line is created and dragged instead of the actual point. Specifically, the problem seems to occur most often at the end of lines.

It appears to happen on zoom levels of 130% and below. I have not been able to replicate it at 200% zoom. But it is very intermittent, where clicking and dragging in the same place in the circle may create a new point, have no effect, or allow for the intended action. I have included a picture indicating the points that I am referring to.

![image](https://cloud.githubusercontent.com/assets/2807247/7446074/e90bc524-f1cb-11e4-8340-a00e36743c11.png)

**Comment by afdia** [comment]
Thanks for the explanation
Based on the image I assume you have multiple relations which are overlapping (partially).
Perhaps the problem only occurs in such cases where the program cannot determine which relation has selection priority (as you can see the selected relation is in the background, because the blue circles are visible but the relation line is not colored blue which it should be usually)

Could you please attach a sample diagram where I can reproduce the issue? I guess it would be sufficient to save only the relations from the picture in an uxf file if you don't want to (or are not allowed to) share the whole diagram.

**Comment by kpdowns** [comment]
Unfortunately, I am unable to share the diagram in its entirety. I have removed all classes leaving only the relations as requested, but I am not able to upload that in direct reply to this thread. As a result I have included a Dropbox link to only the relations in the file.

https://www.dropbox.com/s/a0xoo3qlhy7jp2x/relations.uxf?dl=0

There are multiple relations overlapping in that portion of the diagram, however, the problem still exists on only single lines as well, albeit, less frequently.

**Comment by afdia** [comment]
Thanks for sharing the relations

I have recreated the issue in a diagram with only 2 relations: https://gist.github.com/afdia/f3406d3baec934b00874

Steps to reproduce the issue:
1. select the lower relation (by clicking on the bottom arrow)
2. move the upper ending of the lower relation by dragging the circle or move the lower relation by dragging on the box
-> instead you will drag out a new point of the upper relation

The problem is that the upper relation has selection priority, therefore it gets selected and the new point is dragged out instead of moving the ending of the previously selected relation.
To fix the problem, an already selected relation must have priority over other relations if both are selectable on the mouse position.

**Comment by kpdowns** [comment]
Pleasure. Thank you for being able to assist. That appears to be the problem I was experiencing.

**Comment by afdia** [comment]
I've fixed the issue and added a more complex example to the Gist:
https://gist.github.com/afdia/f3406d3baec934b00874#file-issue260_complex

From v13.3 on overlapping relations should be simpler to handle.
