### ISSUE TITLE
Text above relations incorrect when exporting to pdf.

### ISSUE THREAD

**Issue by kpdowns** [umlet/umlet#261]
Hi,

An issue I have encountered recently involves text above relations. When the chevron is used, it is not included in the exported pdf version. This problem does not exist when exporting to other formats.

I have attached an image demonstrating the issue.

![untitled](https://cloud.githubusercontent.com/assets/2807247/7446335/231d9de2-f1d5-11e4-927c-45ed177ded4e.png)

The problem does not appear to depend on the pdf viewer used. It is present in Microsofts default pdf viewer on Windows 8.1, Adobe Acrobat and SumatraPDF.

OS: Windows 8.1

**Comment by afdia** [comment]
unfortunately this is due to the fact that pdfs don't embedd the font by default and the chevron is an UTF8 character which is not available in the default font (at least on Windows)

As a workaround, the pdf export font can be overwritten (which will then be embedded into the pdf) as seen in #250

For the future it would probably be better to avoid the UTF8 character and perhaps instead draw a triangle manually, although it would not look as good as the UTF8 character.

**Comment by tdevaucoup-invn** [comment]
This problem has been resolved with issue https://github.com/umlet/umlet/issues/195 and a font which support Unicode (like Arial Unicode MS font).

**Comment by afdia** [comment]
Thats correct. I'll close this issue and leave #426 open as a reminder that there may be a better solution in the future (e.g. these specific triangles could be drawn by hand instead of using the UTF8 character, then it would work without embedded font)
