### ISSUE TITLE
UMLEt to java

### ISSUE THREAD

**Issue by gowthamapriya** [umlet/umlet#269]
Hello,

good day,

UMLet is very user friendly and more helpful for students. 

i am student in OVGU,Magdeburg. i am trying to use UMLet for my master thesis. My goal is to generate a SQL for ADAPT notations. so in UMLet i could able to create my own palette for ADAPT. now i have 2 doubt.

1. how to include that own palette in eclipse plug in.

2. if i draw a diagram in stand alone UMLet, how i can export so that i can use in java code to transform to SQL?

Thank you in advance 

Regards

Priya.

**Comment by hirzraimund** [comment]
Hi,

1) As far as i know it is sufficient to add the palette to the palletes folder in the jar archive of the plugin. Any software that can add files to a zip-archive should do the work eg. "Windows Explorer" or Winrar.


2) From the FAQ (http://umlet.com/faq.htm)
Can I create code from UMLet's uxf-files?
UMLet does not provide means to create code from the model, or vice-versa. However, UMLet's uxf file format is a very simple XML format; you can easily parse it with, eg, XSLT, to process the model.
UMLet is aimed at fast UML sketching---we do not plan to support code creation or round-trip engineering in the future.

How does UMLet's uxf-format work?
UMLet's file fomat is a very simple XML format. Note: relations and their stickyness to elements are defined implicitly, ie, if a relation's end point lies on the border of an element, it is regarded as connected to that element.

Best Regards

**Comment by gowthamapriya** [comment]
thank you hirzraimund.

**Comment by afdia** [comment]
Thanks @hirzraimund for answering the question.
The only thing I want to add is: old (deprecated) and new elements look slightly different in the XML. Old ones are referenced by package+classname (which is not very friendly to refactoring) and new ones are reference by a unique ID.
If you want to catch both types you should keep that in mind.

**Comment by gowthamapriya** [comment]
thank u ...

**Comment by gowthamapriya** [comment]
i am new to UMLet, ur comments helped me a lot... thanks...

i have one more question 

i have creater my own pallete and i have drawn diagram using my pallete .

if you XML file of my diagram it includes all the java code what i have used to create a pallete. 

is it any way to wrap my creation code under some function or name ?

Thank u in advance

Priya.

**Comment by afdia** [comment]
you should only see java code within UXF files if you used CustomElements.
Normal elements should only have an ID, the properties and some more info like position, size, ...

There is no way to wrap CustomElement code into a function and reference it, but if you really need fully customizable selfmade elements, you could also check out the UMLet sourcecode and extend NewGridElement with your one implementation and use a specific ID for it.
Of course this would be more complicated and you would have to share the compiled umlet.jar instead of only palette files, but you would could create any element you want with it ;)
