### ISSUE TITLE
Please follow base dir specs on linux

### ISSUE THREAD

**Issue by ManuelSchneid3r** [umlet/umlet#273]
> There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME. [...] $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

![proof](http://i.imgur.com/SRu93Ro.png)

**Comment by ManuelSchneid3r** [comment]
Found out that this is just a wrong fallback. Setting $XDG_CONFIG_HOME works fine. But the in case of  $XDG_CONFIG_HOME either not set or empty, a default equal to $HOME is used instead of $HOME/.config, which is not standard conform.

**Comment by afdia** [comment]
Just to make sure, it should be "~/.config/UMLet/umlet.cfg" instead, right?
We know that the config dir structure is currently not 100% correct, but we have not changed it to keep backwards compatible.
Perhaps the directory "UMLet" should also be called "umlet" but on Windows "Umlet" would be more typical.

**Comment by smumm** [comment]
There is no 'one standard' for the location of configuration files:
- on Windows the path should be the same as given by %LOCALAPPDATA% environment variable, this is "~/AppData/Local" in most cases 
-> "~/AppData/Local/UMLet/umlet.cfg"
- on MacOSX the path should be "~/Library/Preferences" as defined here: https://developer.apple.com/library/mac/qa/qa1170/_index.html 
-> "~/Library/Preferences/UMLet/umlet.cfg"
- on Linux, Solaris, FreeBSD the path should be the same as given by $XDG_CONFIG_HOME environment variable otherwise "~/.config" -> "~/.config/UMLet/umlet.cfg" (XDG_CONFIG_HOME should be set to "~/.config" in most cases)

Backwards compatibility is another story. Keep in mind that this application is made for developers and these developers should be competent enough to move the old config file to the new location. Shouldn't they?

**Comment by ManuelSchneid3r** [comment]
>There is no 'one standard' for the location of configuration files.
True, but this is all the magic beyond platform independance, isn't it? I am not sure if Java has a settings framework. Qt is commendable and does it really well. Check http://doc.qt.io/qt-5/qsettings.html

> Keep in mind that this application is made for developers and these developers should be competent enough to move the old config file to the new location. Shouldn't they?

This argumentation has some flaws. 
 * Yes developers are competent enough, but is this the reason why they have to move stuff an app has not initialized correctly (and set environment variables) ?
 * Backward compatibility is not an argument. You can still read form $HOME/umlet if $HOME/.config/umlet does not exist. Thousands of other apps managed the switch to adhere to the freedesktop basedir specs (especially since they consider backward compatibility)
 * This is an issue. Do you really want to _never_ change it?

**Comment by smumm** [comment]
I agree with you and I would change it to get it working correctly on all plattforms. But finally the repo owner needs to accept my changes. And yes I've fully understood your position.

**Comment by afdia** [comment]
Thanks to @smumm this will be part of v14 (if there are any problems with the current implementation from @smumm please let me know, but I think it should be fine)
