### ISSUE TITLE
Umletino: Diagram has invalid element

### ISSUE THREAD

**Issue by SunSeaAndPalms** [umlet/umlet#281]
Hi,

I am not able to open .uxf file in Umletino 13.3 that has been saved via Umlet 13.3 on Windows. The error msg  is: "Diagram has invalid element: com.umlet.element.custom.Node .....". I can't share the original diagram, however I've built a smaller one which has the similar error but loads partially instead of not loading at all. The diagram is PNG as .UXF files are not allowed here ![test](https://cloud.githubusercontent.com/assets/3924308/8325459/99673c8c-1a62-11e5-977d-8b355a7f4ba1.png) .

**Comment by afdia** [comment]
Thanks for the report.

We've redesigned all elements in v13 because the old ones were largely copy&paste code and tightly coupled with Swing which doesn't work with GWT (which is used for Umletino)

Therefore Umletino cannot open elements from the deprecated palettes, all in one diagrams and custom elements.
We're working on replacements for the all in ones and custom elements, but all of the deprecated ones should have a fitting replacement in one of the new palettes.

**Comment by afdia** [comment]
To make things clear we will show a notification if a diagram contains content which cannot be loaded by Umletino (therefore I've reopened the issue)

**Comment by afdia** [comment]
I've checked it and it should already show an errormessage at the top if an old element is opened, therefore I will close this issue again ;)

![unbenannt](https://cloud.githubusercontent.com/assets/8770707/8337565/3afc69f2-1aac-11e5-9c8f-47b1ed8ba9a5.png)
