### ISSUE TITLE
UMLetino: Lasso does not work

### ISSUE THREAD

**Issue by gerritgriebel** [umlet/umlet#288]
From the FAQ:

> How to lasso-select multiple elements?
> Hold Ctrl, press the left mouse button, and select a rectangle containing the desired elements.

Does not work in UMLetino for me, i.e. Mac OS Chrome, Version 45.0.2438.3 dev (64-bit). Instead the right click menu opens on Ctrl-mouse left click.

Ctrl-left mouse click to select individually multiple objects works, although right click menu opens as well, which is not intended.

**Comment by afdia** [comment]
unfortunately there are some features missing in umletino at the moment:
undo/redo
lasso selection
custom elements
all in one diagrams
java->class diagram generator
export formats other than png

we're currently working on custom elements and all in one diagrams, but undo/redo and lasso will probably be the next ones on our list

the contextmenu on right click is intended, because you can copy/delete/... multiple elements at once or group them together

**Comment by gerritgriebel** [comment]
Still waiting for a fix :) And yes the answer two years later: the right-click menu still opens on a left click on Mac OS Chrome 60.0.3112.101

**Comment by robinsonkwame** [comment]
bumping due to interest in the tool on a mac

**Comment by afdia** [comment]
Good news: we are currently working on the lasso functionality for umletino and vscode plugin. It should be part of the next version
