### ISSUE TITLE
Provide umlet as a feature and a p2 (update) site.

### ISSUE THREAD

**Issue by cniweb** [umlet/umlet#289]
Please provide umlet as a feature and a p2 (update) site.

**Comment by dhartford** [comment]
Also requesting P2/update site.  This will make it possible for consumers using Oomph to pre-package installs to include Umlet as part of the deploy, otherwise would default to other UML diagramming tools that have P2 repos (which, hey, umlet is quick and easy to use, just not quick and easy to package into eclipse atm).

**Comment by dhartford** [comment]
Proof of concept: https://github.com/dhartford/p2-umlet

Would work if you have a local maven repo containing the plugin artifact, otherwise non-portable solution. Opened ticket for the systemPath approach here: https://github.com/reficio/p2-maven-plugin/issues/102

**Comment by afdia** [comment]
Sorry for the late reply, I'm currently busy and do not have much time for UMLet.

I have tried your repository and was able to install the UMLet plugin.
Are the 14 commits sufficient to setup the p2 repo and local maven repo or do I have to do setup anything else to make the p2 repo available at **https://raw.githubusercontent.com/dhartford/p2-umlet/master/repository/**? I'm just asking because I only have limited experience with both types of repos (only as a user)

I guess I will have to sort out how the repository is automatically updated on releases but other than that I like your solution.

Thanks!

**Comment by afdia** [comment]
Thanks for the support in implementing this feature, the next versions of UMLet will provide a p2 update site
