### ISSUE TITLE
Notes do not text wrap anymore in UMLetino 14.0

### ISSUE THREAD

**Issue by sebastien** [umlet/umlet#304]
The latest version of UMLetino does not wrap the notes content anymore.

![screenshot from 2015-08-12 09 58 15](https://cloud.githubusercontent.com/assets/14598/9225685/b8d9e154-40d8-11e5-86f1-48e0396258c7.png)

**Comment by afdia** [comment]
Hi
Although we try to avoid backwards incompatible changes as much as possible, this one was intentional, because before it was not possible to set non-wordwrap non-autoresize to the notes nor text element.

To keep it simple and avoid an additional command which reverts special style like autoresize or wordwrap, we decided to simplify the logic to:
every element which can change style has a default of nonwrapping nonautoresizing
some elements have autoresize as default but only if any other style wouldn't make sense (e.g. UML Actor)

This avoids the need for a separate command to undo wordwrap and the element style has a logic which is easy to remember

Therefore please add "style=wordwrap" and it will work as before
