### ISSUE TITLE
Can I print with datetime?

### ISSUE THREAD

**Issue by lezo524** [umlet/umlet#309]
Normally I need to print with datetime. Is there any option or need to patch?
(I don't use any 3rd party printing tool. like fineprint or sth.)

I do it with my handwriting right now.

**Comment by afdia** [comment]
What do you mean with "print with datetime"?

**Comment by lezo524** [comment]
It means "printing date."

**Comment by afdia** [comment]
Where should it be printed? At one side of an exported diagram?

**Comment by afdia** [comment]
Or to clarify: you want a timestamp printed at the bottom of an exported diagram?

**Comment by lezo524** [comment]
Yes. top left or right is preferable but bottom is ok.

**Comment by afdia** [comment]
Ok thanks I understand
I'm not sure if we will implement it because it's very specific and we want to avoid feature-overload, but I will leave this issue open for other people to comment

**Comment by lezo524** [comment]
Thank you. I appreciate it very much and good to know the tip.

**Comment by hampelratte** [comment]
I saw this request and since I played around with custom elements today, I wrote this custom element:
```java
java.util.Calendar cal = java.util.Calendar.getInstance();
java.text.DateFormat df = java.text.DateFormat.getDateTimeInstance();
printCenter(df.format(cal.getTime()), textHeight());
```
This will print the current timestamp. You can place it whereever you want and it automatically updates as soon as you change something in the diagram. Maybe this is good enough for you.

Just open the diagram, choose Custom Elements -> New... from the menu and enter the code in the Code section.
