### ISSUE TITLE
Custom element function printFixedSize has not had zoom bug fix applied

### ISSUE THREAD

**Issue by iainweir** [umlet/umlet#322]
Custom element function printFixedSize has not had zoom bug fix applied.

The line 
texts.add(new Text(s, x, y, AlignHorizontal.LEFT, fixedFontSize));
should be changed to 
texts.add(new Text(s, (int) (x * zoom), (int) (y * zoom), AlignHorizontal.LEFT, fixedFontSize));
This is inline with the other print functions.

**Comment by afdia** [comment]
Hi

Actually this is not a bug, because the printFixedSize method was planned as some kind of an overlay which should not change size while zooming (like streetnames on a map)

But we've not really finished this because of other features and because it's not that useful.

I've tried applying the zoom to the coordinates but the text looks weird afterwards because the textsize still doesn't change which results in overlapping lines (in case of a multiline string)
What is your usecase for this method where zooming looks correctly?

**Comment by iainweir** [comment]
I was experimenting with custom elements, when I experienced some inconsistencies.
In retrospect I may have been too quick to raise this.
