### ISSUE TITLE
Improve Eclipse Integration

### ISSUE THREAD

**Issue by ruediste** [umlet/umlet#346]
I miss the following functionality from the Eclipse integration:

1. Builder: Automatically export all .uxf diagrams to .png
1. Content assist for linking to existing diagrams from JavaDocs (insert `<img>` tags)
1. Switch between absolute and relative image links
1. add hyperlink to navigate from `<img>` tags to the corresponding .uxf diagram
1. Move and Rename participants to keep `<img>` refs stable
1. option to create a new umlet diagram in `doc-files` as content assist
1. create a maven plugin with the same functionality as the eclipse builder and a corresponding m2e adapter for eclipse

What do you think about these features? I already started working on this and implemented 1-4. Currently I am working on 5. ( see https://github.com/ruediste/umlet/commits/eclipseIntegration  for current status)

**Comment by afdia** [comment]
Hi

@1: A mass export would be helpful, but as I don't know much about Eclipse terminology; what is a builder in the context of an Eclipse plugin and how would I activate it in Eclipse?
@2-5: I guess that would be nice and I would merge it if you want to implement it.
@6: there is already a UMLet specific entry in the "New" dialogue, right? What would be different with your suggestion?
@7: take a look at #274. ykryshchuk already wrote a maven plugin (I have not tested it). Perhaps this is what you need?

In general these are all good ideas which would improve the UMLet usability in Eclipse.
If you want to implement it, just be sure to check the plugin with older Eclipse versions too and especially also with Eclipse version without Java/JDT support. v13.3 had a problem with "Eclipse C/C++" because a change to the plugin included a new JDT dependency which limited UMLet to Eclipse with JDT support. We solved it by making the JDT dependency optional, so perhaps this is a workaround is you need JDT.
Also please document the general usage of classes/methods to make sure future developers understand the code and can change it. The current Eclipse implementation suffers from a lack of documentation which makes changes risky (especially for people without much experience in Eclipse Plugin development)

Btw: As it seems that you have more Eclipse Plugin development knowledge than me, perhaps you can take a look at the UI freeze issues UMLet seems to have with newer Eclipse versions (e.g. #310).
There are some ugly workarounds in the Eclipse integration to make the palette work even if multiple diagrams are opened at the same time.

Good luck and thanks for your help! :)

**Comment by ruediste** [comment]
@1: A builder get's notified whenever a resource changes and is supposed to do some kind of transformation or compilation. For example java compilation is performed by a builder. It would be activated via right-click on project->configure->Add Umlet builder.

@6: The idea is: in a javadoc, you write fore example `overview`, hit ctrl-space and select `New diagram doc-files/overview.uxf`. The umlet diagram get's created, an image link to it is added to the javadoc and the new diagram is opened.

@testing: I'll check it with older versions and with C/C++

@UI freeze: I'll see what I can do.

Thanks for your feedback :-)

**Comment by ruediste** [comment]
Eclipse version: which old version(s) should I test?

**Comment by afdia** [comment]
Is this question about a specific API feature which you want to use? II would say Eclipse Juno should work, because it's the first official 4.* release (according to https://en.wikipedia.org/wiki/Eclipse_%28software%29)

But you can also test Eclipse Helios, because the IBM RAD 8.5 is based on this version and was only replaced in 2013 (according to https://en.wikipedia.org/wiki/Rational_Application_Developer)
But this would be mostly for documentation (if someone has a problem with older Eclipse versions we should know if it should work)
