### ISSUE TITLE
bg attribute not applied to text element (no background color)

### ISSUE THREAD

**Issue by simple2** [umlet/umlet#362]
when adding bg attribute to an text element the element does not have that background color

**Comment by afdia** [comment]
This is intentional, because the background color only colors backgrounds of drawn elements (such as the class box, usecase box or the head of the actor) but it doesnt fill the background of the whole element

If you want such a behavior you could use the following customization which draws a rectangle with a white border around the whole element:

Change
```
This is a text element to place text anywhere.
style=wordwrap
```
to
```
This is a text element to place text anywhere.
style=wordwrap
customelement=
drawRectangle(0,0,width,height) fg=white bg=red

```

**Comment by simple2** [comment]
Thank you for the answer and the way to get the wanted result :-)
