### ISSUE TITLE
Save files to and Open files from iCloud 

### ISSUE THREAD

**Issue by FrazJ** [umlet/umlet#398]
I tend to save a lot of my project files on iCloud so that I can access them from all my devices, and other peoples devices if I don't happen to have mine with me. The problem I have is I have to remember to move the files in and out of iCloud as I work on them, as I can't access it directly from UMLet. 

Would love UMLet to see the iCloud drive!

**Comment by FrazJ** [comment]
Although, I have literally just found you can access these documents through;
User > Library > Mobile Documents > com~apple~CloudDocs 

Maybe this should be closed now? Or changed to be 'Improve the file dialogue box to be the default MacOS version'

**Comment by afdia** [comment]
I guess we have to depend on the filesystem integration of the cloud storage, otherwise we would end up with specific code for google drive, dropbox, icloud, ...
Improving the file chooser dialogue is probably quite difficult as long as we use Swing for UI stuff. It's ugly but it works on every OS with a JVM. ;)
