### ISSUE TITLE
Allinone ActivityDiagram: Foreground and background color don't work

### ISSUE THREAD

**Issue by michburkhalter** [umlet/umlet#407]
AllInOne Activity Diagrams can not be colored. Neither foreground color nor background color have any effect.
![new](https://cloud.githubusercontent.com/assets/5415824/19997970/4980e4ac-a26a-11e6-87d1-9eb2cf9826fd.png)

Win7, 64Bit, Umlet 14.2

**Comment by afdia** [comment]
Thanks for the report, the activity all in one is the only element which has not been redesigned yet (therefore it's also the only one which doesnt exist in umletino).
The old elements miss several features such as bg/fg customizations, ctrl+space autocompletion, ...

It's also not easy to add these features due to the way the elements are designed, therefore we won't fix it there but instead redesign the activity all in one as soon as we find some time.
