### ISSUE TITLE
Allow fontsize > 100

### ISSUE THREAD

**Issue by robertlugg** [umlet/umlet#408]
I would like to create larger texts.  It seems like there should be no limit on these sizes beyond what a system supports.  Microsoft Word allows font sizes up to 1638.  Although that seems a bit crazy, I'd suggest not artificially limiting the acceptable size.

**Comment by afdia** [comment]
I have increased the limit to 5000 which should be sufficient. I would still keep the limit because nobody would intentionally create elements which are larger and cannot be read anyway. An unintentional setting could cause lag or other problems, especially with the multi-platform approach of UMLet. Perhaps Swing can handel fontsize=1000000, but maybe the internet explorer or any other browser (in umletino) cannot.
