### ISSUE TITLE
Edit on doubleclick, duplicate on Ctrl+D

### ISSUE THREAD

**Issue by jekuno** [umlet/umlet#424]
*Observed*: Doubleclicking duplicates an element. User needs to press Enter to edit element.
*Expected*: From comparable software (e.g. text boxes in Office progams or Vector Graphics software) I am used to doubleclick an element to edit it. Could we make this the new default for UMLet as well (or at least add a toggle to the settings to enable this keyboard mapping)? The duplicate function could then be mapped to CMD+D for Mac, CTRL+D for Linux/Windows which is the usual shortcut for duplication as we know it from other software.

**Comment by afdia** [comment]
I see your point, but doubleclick to copy is used since many years in UMLet and nobody has found it problematic, so I guess we will leave it as it is for now (I leave the issue open for some time to collect other opinions on the topic)

**Comment by jekuno** [comment]
Thanks for your detailed answer. I introduced umlet to several newbies recently and literally everyone intuitively doubleclicked in order to edit the items (as they are used to "inline editing").

After reading your explanations I have an even better idea: Would it be possible to activate the properties input as soon as a user selects or places an element. You already show the text of the currently highlighted element in the properties box - if you would also place the cursor in the box that IMHO would improve the usability a lot as users could start typing immediately (and new users wouldn't need to learn that they need to press ENTER first).

**Comment by afdia** [comment]
That would disable all keyboard commands which act on the diagram and not the properties (e.g. moving elements around with arrows keys or even more important copy and pasting elements with ctrl+c/v)

I could imagine that it jumps into the text as soon as the user starts typing anything which is not a known keybinding on selected elements, but then we would have to guess the correct cursor position where he wants to type.
Also it may seem unintuitive that e.g. "down arrow" moves the element on the diagram but "a" types an a into the properties of an element instead of moving the cursor.

I guess a deliberate action to switch from "diagram editing" to "text editing" is still the best way of handling the issue but perhaps we will find a better way in the future

**Comment by jekuno** [comment]
I think "guessing the cursor position" wouldn't be necessary. It would be sufficient to do the same what happens when a user presses "Enter".

However I agree that it wouldn't be coherent if some keypresses apply to the properties window and others apply to the selected element. So we should forget about this idea.
