### ISSUE TITLE
Line wrap in properties editor

### ISSUE THREAD

**Issue by perlyking** [umlet/umlet#429]
Text in properties box (left bottom of screen) is not line-wrapped. This makes it hard to type in long comments as they scroll off the right of the box. The user is forced to write very short sentences, separated by carriage returns.

![image](https://cloud.githubusercontent.com/assets/1415628/22687056/6d4cd4a0-ed1e-11e6-8a3e-b303a675408a.png)

**Comment by afdia** [comment]
It should scroll to the right (and a horizontal scrollbar should appear) if the sentence is too long.

I do not agree that the user is "forced to add carriage returns", because you can simply watch the element while writing instead of watching the properties textarea (as you're using style=wordwrap it will add linebreaks automatically and the whole text is visible).

The problem with adding line-wrapping in the properties text is that it would add linebreaks for readability which are not represented within the element when not using style=wordwrap.
And even elements with style=wordwrap will add linebreaks at other positions than the properties (because the width of the element must not be the same as the width of the properties).

I guess an option to enable automatic linebreaks in the properties would be OK, as we also allow to specify the fontsize and some other properties area settings

**Comment by perlyking** [comment]
Many thanks for considering my idea and your reply. Yes, the properties text does scroll to the right, but for long sentences this is in my opinion rather un-ergonomic as a large part of the text you are writing will be obscured at any one time, which, after all, is the reason we have line wrap in other editors.

> you can simply watch the element while writing instead of watching the properties textarea

Yes: you can watch the (note) element while you type, but it's an unusual way to edit text (i.e. type in one box while watching another), and moreover does not help in the situation where you want to edit existing text and are forced to scroll the properties text to locate the correct cursor insertion point.

>The problem with adding line-wrapping in the properties text is that it would add linebreaks for readability which are not represented within the element when not using style=wordwrap.

I think most user will thank you for being able to see the text they are editing more easily, and will understand that the (note) element will display the text differently if they choose not to use `style=wordwrap`

> And even elements with style=wordwrap will add linebreaks at other positions than the properties (because the width of the element must not be the same as the width of the properties).

I'm not sure this would be a problem. I think the user will get the idea that their text is appearing in two places, and being wrapped in each according to the size of the container.

I hope you find my comments constructive: I am a long-time UMLet user and think it's an amazingly elegant and simple tool.

-Chris

**Comment by cdokolas** [comment]
I think wrapping in the properties box is good. I know I need it! It may be helpful to make wrapping toggle-able somehow (e.g. a selection in the `edit` menu or, perhaps, a checkbox in the properties box title bar).

**Comment by afdia** [comment]
I thought it should be quite simple, but was not able to get it to work how I wanted.

If I change OwnSyntaxPane.java in the following way:
```
textArea.setLineWrap(true);
textArea.setWrapStyleWord(true);
```
it looks like this:
![grafik](https://cloud.githubusercontent.com/assets/8770707/25935843/4b666d42-3625-11e7-9460-5aa05dc95630.png)

The main problem is that it wraps on characters and not spaces (I thought wrapStyleWord would work but unfortunately it doesn't - perhaps because UMLet uses a custom syntax for highlighting)
The second problem is that only the current line is highlighted, but not wrapped parts of the line (in the example it should highlight the first 2 lines because both are part of the wrapped line#1) so without added linenumbers (as I have done temporarily for the screenshot), it would be hard to see where one line ends.

I'm not sure if the feature would be useful if implemented in such a way (also we would probably need to make linenumbers and wordwrap customizable because of the highlighting problem)

**Comment by afdia** [comment]
Even with those issues, it's probably nice to have therefore line wrap and numbers can now be configured
