### ISSUE TITLE
Some components show invalid type message on windows 10[version 14.2]

### ISSUE THREAD

**Issue by almerion** [umlet/umlet#463]
![umlet142_components_problem](https://user-images.githubusercontent.com/12101466/27329737-67ddf788-55bf-11e7-82a6-83b2ca42036e.png)

**Comment by almerion** [comment]
![umlet142_components_problem2](https://user-images.githubusercontent.com/12101466/27330187-08791190-55c1-11e7-87dc-65a373e66a25.png)
![umlet142_components_problem3](https://user-images.githubusercontent.com/12101466/27330222-330c3e46-55c1-11e7-8b68-aadf3a80c479.png)

**Comment by afdia** [comment]
Is this an unmodified UMLet 14.2 with default palettes or are these custom palettes?
Nobody has ever reported such problems with palettes, so perhaps it's specific to some part of your system.
Perhaps test it with another Java version or check issue #455 to see if it's the same problem.

Other than that you could try to open UML Activity again in v14.2 (as in the first screenshot) and click on the left element which says "no enum constant". Please enlarge it to see the full error message and check if the properties text matches

> receive
> signal
> type=receiver

The weird thing is that the element below (send signal) is basically the same code just with `type=sender` instead.

**Comment by almerion** [comment]
I think , I found the cause of problem. When I change the all 'i' letters to 'ı' letter everything goes  well.
For example: Some templates is red and they show an error message like this
![noname](https://user-images.githubusercontent.com/12101466/28515311-cf977fbe-7065-11e7-9984-2a28ff896b8e.png)
I retyped "style=autoresize"  property as "style=autoresıze"  

![noname1](https://user-images.githubusercontent.com/12101466/28515494-882f3152-7066-11e7-96ae-ab723e5721d1.png)
and error is gone 
![noname2](https://user-images.githubusercontent.com/12101466/28515496-88717e54-7066-11e7-813c-fca0ca83bf30.png)


My default keyboard layout is Turkish, but I use English layout. (English doesn't have 'ı', but Turkish has that char.)  Maybe this is why some templates show errors.

**Comment by afdia** [comment]
I think you have found the problem. Acording to [1] the toLowerCase method behaves differently when using the turkish locale, therefore I is no longer transformed to i as it would be with english locale.
I was also able to reproduce the issue when changing the Locale on my system to `new Locale("tr","TR")`

The issue should be fixed in the next version (I have added Locale.ENGLISH for all locations where user input is interpreted as a command (such as autoresize) therefore the commands should always be interpreted as english words)

Thanks for the report!

[1] https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase

**Comment by almerion** [comment]
You are welcome buddy.
