### ISSUE TITLE
Transparency settings makes symbol disappear

### ISSUE THREAD

**Issue by WerVbn** [umlet/umlet#476]
Setting the transparency of the bg color of the symbol component to 1, makes the symbol in the upper right corner invisible. Is there a fix available to keep the symbol visible?

I would like to place a component in an rectangle, but I want the bg color of the component to be not transparent and the symbol to be visible. Is that possible?

**Comment by afdia** [comment]
Thanks for the bugreport. The element has drawn the symbol before drawing the border with the background, therefore the background was in front of the symbol.

It will be fixed in the next release.
The only workaround which I can thing of until it's fixed is placing a separate element with the bg color and transparency behind the element with the symbol component and the text (if they overlap exactly it looks like it's one element)
