### ISSUE TITLE
Custom Elements Are Chopped if exported using Ctrl-C Ctrl-V  

### ISSUE THREAD

**Issue by scuzzar** [umlet/umlet#478]
If i create a new custom element (Custom Element -> New... -> Add to diagram and close editor)  and export it (for example to Word) by selecting it and using copy/paste, the bottom line and right line disappear. Here is an example take directly form the out of this diagram. 

The Problem is not present using the File->Export variant.

![image](https://user-images.githubusercontent.com/33227147/32177548-d9cc4f6a-bd8a-11e7-8dd7-2c8514fda071.png)

[new.zip](https://github.com/umlet/umlet/files/1427644/new.zip)

I use the Standalone on a Windows 10 installation.

**Comment by antanasb** [comment]
I can confirm this (Standalone UMLet on Ubuntu GNU/Linux 16.04 and LibreOffice 5.4.2.2)

**Comment by afdia** [comment]
Thanks for the report, it seems like the code in copy to clipboard does something different than the code for export to image (although both should be quite similar)

**Comment by kianimo** [comment]
I can also confirm this. In my case the problem additionally occours on export to image/pdf (Standalone UMLet 14.2 on Windows 7), as afdia expected.
The example image shows how it's rendered in UMLet (left) and as PNG export (right).
![b1](https://user-images.githubusercontent.com/11871710/33658858-77bb59fe-da7e-11e7-868c-41d0153078ab.PNG)

**Comment by afdia** [comment]
I have fixed the problem. It will still occur on high zoom levels (>100%) but they are unusual, therefore I guess it's fine. Unfortunately it's only a workaround because the custom element code is old and hard to understand/maintain.

By the way: for simple customizations, I would suggest to use the the new lightweight customizations (see Custom Drawings palette).
They hav less issues, can be applied to any element, do not compile java code at runtime (which is a potential security risk) and they also work on non-java based umlet platforms such as www.umletino.com
