### ISSUE TITLE
Static tmp file causes errors on multiuser system

### ISSUE THREAD

**Issue by goehle** [umlet/umlet#480]
This is a nice tool and we added it to our computer science dept server for students to use.  Unfortunately when a user opens umlet it creates a temporary file "/tmp/umlet.tmp" owned by that user.  While that file is present other users get lots of error from umlet since they are also attempting to access the same file.  If the original user doesn't close umlet properly (i.e by closing the terminal window) then the umlet.tmp file isn't cleaned up and prevents any other user from using umlet indefinitely.  I suppose the standard fix for this kind of thing would be to add a random string to the umlet.tmp file name.

**Comment by afdia** [comment]
Hi
Unfortunately adding a random string is not possible in this case.

The umlet.tmp file is used to make it possible to open a diagram in an already running UMLet instance instead of starting a new one.
Technically it works like the following:
* When Umlet starts it creates an empty umlet.tmp file and monitors it for changes
* Umlet allows to use a diagram as argument to immediately open it (e.g. to enable double clicking on an uxf file to open it directly)
* When Umlet starts with a diagram as argument, it checks if umlet.tmp exists and if it does it writes the diagram path to the file and quits immediately (this is why Umlet doesn't seem to open)
* The running instance of Umlet which monitors the umlet.tmp file triggers by the path written into the tmp file and opens the file immediately

You can also simulate this by writing any path to an existing diagram (e.g. C:/UML Common Elements.uxf) into the umlet.tmp file and a running Umlet instance will open it

Therefore it is required to use a single filename because it's used as a synchronization mechanism between Umlet instances, but to be honest I'm not a fan of the "sending diagrams to running instances" mechanism, so perhaps we should remove it without replacement and diagrams will always be opened in a new Umlet instance, but the mechanism exists since very early Umlet versions, so I'm not sure what other users think about it.

As a workaround you could avoid adding a diagram path as argument when starting Umlet.

**Comment by goehle** [comment]
Thanks for the response.  It does seem like the setup you describe is somewhat incompatible with multi-user environments.  As far as I can tell the umlet.tmp file permissions issue causes problems whether or not a diagram path is provided (you can test by changing ownership of the test file to root and setting permissions to 700 to see what kind of errors it produces).  I'm sure there is a workaround somewhere, though.

**Comment by ChristophKnabe** [comment]
We at Beuth University Berlin had this problem too. We solved it by passing `-Djava.io.tmpdir=/tmp/${USER}-umlet/` to the command line. According to https://github.com/umlet/umlet/blob/master/umlet-swing/src/main/java/com/baselet/control/util/Path.java#L112 this now user-specific directory will be used as base directory for all temporary files by UMLet. Our Linux-server-specific start script texts as follows, but you would have to adapt the Java and UMLet home directories.
```
#!/bin/sh
# Start script for UMLet for Linux servers. Avoids conflicts WRT file /tmp/umlet.tmp
# See https://github.com/umlet/umlet/issues/480
# Will use directory /tmp/$USER as temporary directory for UMLet.

# activate job monitoring, break at undefined variables or erroneous completion.
# @see: http://www.linuxforums.org/forum/programming-scripting/139939-fg-no-job-control-script.html
set -mue

if [ $# -eq 1 ] ; then
  _UMLET_OPTS=-filename="${1}"
else
  _UMLET_OPTS="$@"
fi

#Set user-specific temporary directory to avoid issue #480
#This will be evaluated by https://github.com/umlet/umlet/blob/master/umlet-swing/src/main/java/com/baselet/control/util/Path.java#L112
userTemp=/tmp/${USER}-umlet
mkdir -p $userTemp
java -jar -Dsun.java2d.xrender=f -Djava.io.tmpdir=$userTemp -jar /opt/Umlet/umlet.jar ${_UMLET_OPTS}
```
