### ISSUE TITLE
providing macOS application

### ISSUE THREAD

**Issue by barthel** [umlet/umlet#499]
This topic was earlier discussed in #495 and moved into this new issue.

**Comment by barthel** [comment]
I prefer to generate the macOS application while the Maven build.

There are two options.
1. Providing the App itself (like the EXE file)
2. Providing a installer like image (PKG or DMG file)

https://github.com/federkasten/appbundle-maven-plugin

A second goal is to support [Homebrew](https://brew.sh) and/or [Caskroom](https://caskroom.github.io) in a easier way.

**Comment by barthel** [comment]
The App itself is more or less an directory.
The distribution for macOS will provided by a disk image file (.dmg).
This kind of container is like an installer on macOS.

**BUT** the Maven plugin can build the dmg container only on macOS or Linux.

**Comment by afdia** [comment]
I guess it would be a convenient approach for users because they don't have to install Java in order to use Umlet, but I'm not sure if it's the best approach.
* the output file is probably huge until we modularize Umlet using Java9
* we would have to provide a separate file for MacOS while the normal umlet package would still work
* even if Umlet doesn't start a web server or something potential dangerous, packaging a JRE means that we would be responsible to keep the JRE up to date

Perhaps it is a nice approach for the future if Umlet is modularized using Java9 and the embedded JRE overhead is less severe, I tend to stay with the current packaging for the moment.
A nice article about the topic: https://steveperkins.com/using-java-9-modularization-to-ship-zero-dependency-native-apps/

What do you think? Have you tried it and checked the size of the output with a packaged JRE?

**Comment by barthel** [comment]
I played around with the ```appbundle-maven-plugin``` and it is more or less a pain.
The structure of UMLet and the conventions of the plugin making it very difficult to build a well formed application.

I'm not a big fan of a embedded JRE. Like the generates EXE file, the macOS doesn't require a embedded JRE and works with a installed Java version instead.

My conclusion for now, it is not useful to build a macOS application based on that  conditions.
