### ISSUE TITLE
Cannot download UMLet on Eclipse Marketplace

### ISSUE THREAD

**Issue by hcsradek** [umlet/umlet#542]
Unable to read repository at https://www.umlet.com/umlet_latest/repository/content.xml

**Comment by afdia** [comment]
The repository url is: https://www.umlet.com/umlet_latest/repository/

**Comment by hcsradek** [comment]
Hi,

But the download via Eclipse market does not work either (the previous error was generated by older version of Eclipse).

Pozdrawiam,
Radek Hofman

**Comment by afdia** [comment]
If i remember correctly, Eclipse Mars or newer should be supported, and the statistics show that ~1400 people installed it last month via the marketplace, so it should work in theory.

Perhaps there are temporary issues or you should try a newer eclipse version.
Also you can add the update site manually (Help > install new software > add https://www.umlet.com/umlet_latest/repository/) and install it from there instead of using the marketplace
