### ISSUE TITLE
CustomElement has error when running UMLet standalon on OpenJDK 12.0.1

### ISSUE THREAD

**Issue by swissbison** [umlet/umlet#546]
Hello,
I had to run UMLet standalone 14.3.0 using OpenJDK 12.0.1 due to some License issues in our Company. Everything worked fine so far, but when I wanted to create a custom element, I found out thet there is an error occuring ...
![CustomElement-using-OpenJDK12 0 1](https://user-images.githubusercontent.com/22021259/59911039-60277980-9413-11e9-8b6d-cc4fb3a744bf.png)

PS: I have done the same test using the Eclipse Plugin (Eclipse V2019-06 running on OpenJDK 12.0.1) where everything worked fine …

Cheers and Thanks for your work!
Paul

**Comment by afdia** [comment]
This is a problem with the eclipse compiler we're using to compile custom elements and some new java versions.

I have updated the compiler, so it will be fixed in the next release.
In the meantime, you can patch it for yourself by:
1. Download the new ecj version from https://mvnrepository.com/artifact/org.eclipse.jdt/ecj/3.18.0 (click on the jar download link)
2. Rename the downloaded file to ecj-4.4.2.jar
3. Replace the file <umlet_dir>/lib/ecj-4.4.2.jar with the downloaded jar file

(don't worry about the lower version number, the compiler is available in 2 different versions in maven, so 3.18 is the newer one, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=499019)

**Comment by swissbison** [comment]
Thank you for your fast response!

Your workaround worked flawlessly!!


Cheers

**Comment by rzfzr** [comment]
I still had to apply the workaround, on version 14.3
Just realized that the last release was in 2018... but development looks somewhat active, what's going on?
