### ISSUE TITLE
Umlet.exe/launch4j does not find custom JRE/JDK (Windows)

### ISSUE THREAD

**Issue by alexandroid** [umlet/umlet#548]
This is somewhat related to [492](https://github.com/umlet/umlet/issues/492) but different. Steps to reproduce:

1. Download standalone Umlet 14.3.0 for Windows & unzip it.
2. Install a custom JRE (e.g. [Amazon Corretto 8](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html))
3. Set `JAVA_HOME="C:\Program Files\Java\amazon-corretto-8.222.10.3-windows-x64-jre"`

Try launching `Umlet.exe --l4j-debug-all` and get an error `This application requires a Java Runtime Environment 1.6.0`.

Technically it's a [bug 127](https://sourceforge.net/p/launch4j/bugs/197/) on `launch4j` side which checks for a bunch of registry keys for the JRE/JDK path but does not fall back to `JAVA_HOME`.

But it will require Umlet to update whenever launch4j fixes it. Or Umlet could consider this its own problem and try to fix it by bundling the JRE or using a different wrapper, if it exists, that checks for `JAVA_HOME`.

For details, `launch4j.log` it creates:

```
Version:	3.12
CmdLine:	C:\Users\User1\Progs\Umlet\Umlet.exe --l4j-debug-all
WOW64:		yes
Resource 10:	<NULL>
Resource 22:	<NULL>
Resource 101:	An error occurred while starting the application.
Resource 23:	<NULL>
Resource 8:	<NULL>
jreSearch()
Resource 32:	<NULL>
Resource 2:	1.6.0
Java min ver:	1.006.000
Resource 3:	<NULL>
Java max ver:	
bundledJreSearch()
Resource 29:	<NULL>
Resource 1:	<NULL>
installedJreSearch()
Resource 18:	1
findJavaHome()
Resource 30:	2
64-bit search:	SOFTWARE\JavaSoft\Java Runtime Environment...
32-bit search:	SOFTWARE\JavaSoft\Java Runtime Environment...
64-bit search:	SOFTWARE\JavaSoft\Java Development Kit...
32-bit search:	SOFTWARE\JavaSoft\Java Development Kit...
64-bit search:	SOFTWARE\JavaSoft\JRE...
32-bit search:	SOFTWARE\JavaSoft\JRE...
64-bit search:	SOFTWARE\JavaSoft\JDK...
32-bit search:	SOFTWARE\JavaSoft\JDK...
64-bit search:	SOFTWARE\IBM\Java Runtime Environment...
32-bit search:	SOFTWARE\IBM\Java Runtime Environment...
64-bit search:	SOFTWARE\IBM\Java Development Kit...
32-bit search:	SOFTWARE\IBM\Java Development Kit...
64-bit search:	SOFTWARE\IBM\Java2 Runtime Environment...
32-bit search:	SOFTWARE\IBM\Java2 Runtime Environment...
64-bit search:	SOFTWARE\IBM\Java Development Kit...
32-bit search:	SOFTWARE\IBM\Java Development Kit...
Resource 103:	This application requires a Java Runtime Environment
Resource 21:	http://java.com/download
Error msg:	This application requires a Java Runtime Environment 1.6.0
Open URL:	http://java.com/download
```

**Comment by afdia** [comment]
Thanks for the report, previous versions of umlet used a custom exe wrapper and it caused at least as many problems with specific system setups, therefore we switched to launch4j to avoid those problems, but it seems that Java client software which relies on a local Java installation is harder than one might think.

I hope they will fix the bug soon and we can provide a new exe with the next release.

Maybe we can bundle a minimal JRE in the future (using [Javapackager](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/packager.html)) which will probably solve most problems, but will also increase the download size of UMLet.

**Comment by MinnieTheMoocher** [comment]
This bug is especially annoying if you use e.g. AdoptOpenJDK 1.8.0_212 instead of Oracle Java.

Workaround: set JAVA_HOME environment variable

**Comment by Laro88** [comment]
It would make me oh so happy to get the exe rulling with non Oracle installs. We have an "Oracle issue" at work so we can't use Oracle baked installs of java.

umlet.jar works fine, however our file archive system need an executable to open the uxf file so running java -jar umlet.jar is not sufficient.
This config behaves fine.
```
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**Comment by afdia** [comment]
Unfortunately the last launch4j release is 1,5 years old and the issue is still open, so we cannot provide a fixed exe.
Maybe you can download launch4j and try to build an exe file. If you have a working solution, let me know what settings I have to use and I can generate the fixed exe and include it in the next Umlet release.

Otherwise maybe a simple .bat file which calls "java -jar umlet.jar" could fix your problem?

**Comment by loicdecl** [comment]
Hi afdia,
I really appreciate UMLet and I am trying to expand it in my company. The fact to install Oracle Java was clearly an issue for this as we have clear instructions to move away from it.
I created a bat file in my install with the command you suggest, and it works perfectly !
I can create a shortcut in my desktop to avoid picking it in the install dir.
Thanks for the tip 

Loic.

**Comment by loicdecl** [comment]
Hi all,
I found a way to make it work with the release of OpenJdk 8 that is provided by the AdoptOpenJDK community (https://adoptopenjdk.net/). 
Before starting the installation, you must enable the creation of 'JAVA_HOME' and the 'JavaSoft' register key, which are disabled by default.
You can see an exemple is the attached image below. The options are in French but you can deduce it from the keywords I gaved before.
Cheers,
Loïc.

![AdoptJdkInstall](https://user-images.githubusercontent.com/48792155/69970483-9d457b00-151e-11ea-996d-0afd9849b6f9.png)

**Comment by v-rosa** [comment]
Seems that launch4j already fixed the issue. See http://launch4j.sourceforge.net/changelog.html

> Changes in version 3.13 (03-02-2021)
>   * FR [#127](https://sourceforge.net/p/launch4j/feature-requests/127/?page=1) Added multiple bundled JRE path search (%JAVA_HOME%).

**Comment by afdia** [comment]
Thanks for the reminder!

I have recreated the exe with launch4j 3.14 and used the suggested method from https://sourceforge.net/p/launch4j/feature-requests/127/?page=1 which uses the following path:
**%JAVA_HOME%;%PATH%**

That way it uses JAVA_HOME if set, otherwise the java installation using the PATH and if both fail still tries to find a Java installation using the usual process (I guess it's based on Windows registry keys)

Also if Java still cannot be found it redirects to https://adoptopenjdk.net/ instead of the oracle website

I hope this will finally fix the issue

You can download the new exe from https://github.com/umlet/umlet/blob/852774cab7c576ebf9f43b14735fb40fde7724c9/umlet-standalone/src/exe/Umlet.exe (click Download) and replace the current 14.2 one to test it

**Comment by sz3lbi** [comment]
After downloading the `.exe` file from the repo, everything works fine for me. Before that, I've just run the app through the `.jar` file like I have described [here](https://github.com/umlet/umlet/issues/492#issuecomment-1016410447) and it worked just fine as well.
The issue is that the standalone package on the [UMLet website](https://www.umlet.com/changes.htm) still has the old version of `.exe`, so I had to Google the issue even if it has been solved months ago.
