### ISSUE TITLE
plugin for Eclipse

### ISSUE THREAD

**Issue by chengm349** [umlet/umlet#558]
If I build its Eclipse plugin jar file, my installed Eclipse can’t show UMLet/Diagram when I select "File/New/Other..". (BTW, the generated jar file is com.umlet.plugin-14.4.0-SNAPSHOT.jar for example.) However if I download the plugin from https://www.umlet.com/, then everything looks ok.

When should I also put umlet-eclipse-plugin-deps-14.4.0-SNAPSHOT.jar under Eclipse plugin folder?

**Comment by afdia** [comment]
Please check out https://github.com/umlet/umlet/wiki/Common-Problems#i-cannot-setupinstall-the-eclipse-plugin

If you build  the parent pom, it also generates the p2 repository (in theumlet-eclipse-p2 project) and you can install Umlet from the local p2 repo

**Comment by chengm349** [comment]
The link tells me how to installed a built plugin in different ways which is not my interests. What I want to achieve is a). download all umlet src and build the Eclipse plugin myself. Then I may use manual way to put the plugin jar file under Eclipse/plugins. This way does not work. However if I downloaded a plugin jar file from www.umlet.com web, then no any problem.

**Comment by afdia** [comment]
To build it you have to checkout the repo and run "mvn clean install". See the Travis build: https://travis-ci.org/umlet/umlet
The Plugin output is in umlet-eclipse-plugin/target/com.umlet.plugin-14.4.0-SNAPSHOT.jar and the p2 update site is in umlet-eclipse-p2/target/umlet-eclipse-p2-14.4.0-SNAPSHOT.zip
These artifacts are uploaded to a simple http server, so there is no additional manipulation and the built artifacts should work

**Comment by chengm349** [comment]
I followed https://travis-ci.org/umlet/umlet and did these actions:

    62  8:54    git clone --depth=50 --branch=master https://github.com/umlet/umlet.git
    64  8:55    cd umlet
    65  8:56    git checkout -qf a02199ac753c8f694640b80a14e9236ad63f7c93
    66  8:56    java -Xmx32m -version
    67  8:57    ls
    68  8:57    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    69  9:07    pwd
    70  9:10    /usr/local/maven/bin/mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

And the attached file has the last cmd result.
[result.txt](https://github.com/umlet/umlet/files/3849473/result.txt)

I copied
-rw-r--r-- 1 mcheng flexusr 9924703 Nov 15 09:51 com.umlet.plugin_14.4.0.20191115095105.jar

to Eclipse/dropins and rename it to be -rw-r--r-- 1 mcheng flexusr 9924703 Nov 15 09:51 com.umlet.plugin_14.4.0.jar

unfortunately still not working.

**Comment by chengm349** [comment]
I got the src by git clone --depth=50 --branch=master https://github.com/umlet/umlet.git
should I try 14.3.0 version because 14.3.0 plugin got from umlet web site is ok.

**Comment by afdia** [comment]
As you see in the result.txt, the build succeeds. If the Plugin doesn't work it is caused by your changes (see #560)
As I've mentioned there, it's quite complicated to combine the platform independent nature of Umlet and the Eclipse Plugin system, so I cannot really help you and you will have to study Eclipse/P2/Tycho documentation to solve the problem.

**Comment by chengm349** [comment]
Dear Andreas :

For this issue, I did not change a single char. the problem is bcos the build succeeds but it does not work. otherwise if the build failed then definitely it can't work. out of the question. I just want to build your original code and see my build can work for Eclipse.

**Comment by afdia** [comment]
If it's the unmodified sourcecode, it should work.
I have just done the following:
1. Downloaded Umlet sources
2. Executed "mvn clean install"
3. Downloaded a clean copy of Eclipse (https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2019-09/R/eclipse-jee-2019-09-R-win32-x86_64.zip)
4. Unzipped Eclipse and copied "umlet-eclipse-plugin/target/com.umlet.plugin-14.4.0-SNAPSHOT.jar" into eclipsedir/dropins
5. Started Eclipse
and everything works, so there should not be any problem with the current state of the umlet repository.

We know about problems with Eclipse which is why we created the wiki page https://github.com/umlet/umlet/wiki/Common-Problems#i-cannot-setupinstall-the-eclipse-plugin
Perhaps it helps, or otherwise try running it on a clean Eclipse installation, it should work (especially if v14.3 also works)

**Comment by chengm349** [comment]
I followed your again and this time I did download a newer Eclipse version. Now it works. thanks.
