### ISSUE TITLE
Your guide for umlet-elements module modification

### ISSUE THREAD

**Issue by chengm349** [umlet/umlet#560]
I tried to modify umlet-elements module so that its source code can also use Eclipse’s lib like what you have achieve in umlet-eclipse-plugin. I copied whole META-INF to umlet-elements, modified pom.xml under umlet-elements (attached here). Also playing a safe game by copying plugin.xml from umlet-eclipse-plugin into umlet-elements as well.

But still failed to find eclipse pkg during umlet-elements compilation:

--- maven-compiler-plugin:3.1:compile (default-compile) @ umlet-elements ---
Changes detected - recompiling the module!
Compiling 214 source files to C:\Users\mcheng\FlexTrade\auto plugin\qfixsoden\umlet-elements\target\classes
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
com/baselet/element/interfaces/GridElement.java:[15,36] package org.eclipse.cdt.core.dom.ast does not exist
com/baselet/element/interfaces/GridElement.java:[88,9] cannot find symbol
  symbol:   class IASTNode
  location: interface com.baselet.element.interfaces.GridElement

BTW, I add org.eclipse.cdt.core to MANIFEST.MF’s Require-Bundle. umlet-eclipse-plugin code can find class IASTNode.

**Comment by chengm349** [comment]
MANIFEST.MF and pom used in my umlet-elements

[pom.zip](https://github.com/umlet/umlet/files/3849945/pom.zip)
[MANIFEST.zip](https://github.com/umlet/umlet/files/3849947/MANIFEST.zip)

**Comment by afdia** [comment]
Sorry, I cannot help you with this. The Umlet sourcecode is carefully separated into several modules (as listed in https://github.com/umlet/umlet/wiki/Information-for-Developers#projectmodule-structure) to make sure it works on every platform.

The Eclipse Plugin platform is especially challenging, because it uses its own dependency system (p2) which makes things very difficult (therefore we use workarounds like the umlet-eclipse-plugin-deps project)

I would suggest to keep the current project structure and keep Eclipse specific stuff inside the umlet-eclipse-* projects, otherwise you will run into problems which may be hard to solve. I cannot help you with this, because I'm no expert of the Eclipse p2 system

**Comment by chengm349** [comment]
I don't have intention to change Eclipse plugin part code which works. I just want to access some Eclipse lib functions in umlet-element. So I thought I can quickly use umlet-eclipse-plugin mechanism like MANIFEST.MF etc. Any suggestion is warmly welcome.

**Comment by chengm349** [comment]
This is a blocking issue in my project. keen to have anyone's kind suggestion.

**Comment by chengm349** [comment]
SOS

**Comment by chengm349** [comment]
Can someone tell me what setting caused target/p2content.xml and target/p2artifacts.xml being generated in umlet-eclipse-plugin. Any setting in pom.xml or what?

**Comment by afdia** [comment]
I cannot help you because I haven't written the Eclipse Plugin portion of Umlet and I'm currently the only maintainer of umlet.

I can only suggest to NOT break the current project structure (see https://github.com/umlet/umlet/wiki/Information-for-Developers#projectmodule-structure). As long as you keep Eclipse specific stuff in the eclipse project it will work.
Otherwise you will have to change the project/module dependencies to be Eclipse/P2/Tycho compatible and read the Eclipse documentation or tutorials on this topic or you can go all the way and remove umlet-gwt and umlet-standalone and put everything else in the umlet-eclipse-plugin. This eliminates project dependencies because everything is now in a single project, but this is just an assumption, I'm not 100% sure that it will work.

This is my last post on this topic, as I cannot help you more than that.
I leave the issue open for some time, because maybe other people may help but **please stop spamming our issue tracker and mail addresses**. We cannot help you more than that.
Thanks!
