### ISSUE TITLE
com.umlet.plugin file name

### ISSUE THREAD

**Issue by chengm349** [umlet/umlet#570]
I followed https://www.umlet.com/faq.htm instruction to put com.umlet.plugin jar file under dropins. It works. However the file name must be for example com.umlet.plugin-14.4.0.jar. If I changed it to com.umlet.plugin.jar, then Eclipse can't open .uxf file. I'd like to know the internal concept or restriction.

**Comment by afdia** [comment]
There is nothing specific about umlet, it's just the default restrictions of eclipse plugins. See all the other plugins in the eclipse/plugins directory which have the version in the name.

Also please don't spam the issue tracker with questions (the last 11 out of 13 issues are created by you).
I try to help out with a question here or there if I'm able to help, but the idea of the issue tracker is to record, track and fix issues and it gets more complicated if there are so many questions (i.e. non-issue tickets)
Umlet is an open source project which has contributions by multiple people and especially the Eclipse part is very old code unfortunately, so you will have to research Eclipse and it's plugin system in order to get good answers.
