### ISSUE TITLE
Embed original diagram (as comment) in png export

### ISSUE THREAD

**Issue by maqroll** [umlet/umlet#577]
I like the powerful simplicity of umletino.
Right now we export every diagram to uxf (for edition) and to png (for visualization).

PRs #575 and #576 will allow us just export uxf because we have an easy way to visualize from it.

Another approach is embed the diagram inside png files as a comment ([spec](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html) section 4.2.3) and allow umletino both to import uxf files or png files with that comment. 

That way we can use png files both for visualization and edition.

What do you think?

Described workflow is feasible using standard tools ([embed diagram in png](https://github.com/maqroll/master/blob/master/bat/embed_file_in_image.bat) and [extract diagram from png](https://github.com/maqroll/master/blob/master/bat/extract_file_from_image.bat)) but I didn't check if the libraries used in umletino support something like this (read and write comment fields in png).

**Comment by afdia** [comment]
I guess setting a png comment won't work because umletino exports the html canvas to png using default canvas operations (I guess it's `canvas.toDataURL('image/png')` which are quite simple and don't offer much customization.

Also I personally don't think a png comment is a good or intuitive place for this, because most people don't know they even exist. I would stick with the png alongside uxf style as you described, because then everyone knows how to edit the diagram (or google what an uxf file is, find out it's for umlet/ino and can edit it). If it's just a png file nobody can intuitively find out how to edit that diagram.

If you use a Wiki or some kind of website, the diagram could be shown as a png which opens the uxf diagram (using the ?uxf param) if you click on the image or it could have an "edit" button at the bottom. This would be easier than opening Umletino manually and dragging a file into it.
