### ISSUE TITLE
Issues with the Initial/Final State Icons and Dark Mode

### ISSUE THREAD

**Issue by pearson** [umlet/umlet#696]
When in dark mode it is hard to tell the difference between the state machine icons for initial state and final state, as shown here:

![image](https://user-images.githubusercontent.com/656880/203857722-f2a9591e-fca7-4d07-9213-58f86a174982.png)
 
When in dark mode, only the outer ring of those two icons is being inverted to white, and the filled part of each icon appears to be remaining black.

**Comment by afdia** [comment]
Thanks for the report, this will be fixed in v15.1 and look like the following (screenshot taken from chrome with dark mode therefore it's a bit darker than your screenshot which is probably from vscode)
![grafik](https://user-images.githubusercontent.com/8770707/215148499-8e19a6cc-a47d-4570-ba9b-c93027810baa.png)
