### ISSUE TITLE
Instance in object diagram does not support attribute with name `type`

### ISSUE THREAD

**Issue by rtaupe** [umlet/umlet#761]
I want to create a UML object diagram containing instances of a class that has an attribute named `type`.

I tried two ways, and both seem to cause problems:

1. com.baselet.element.old.element.Class
```
<element>
  <type>com.baselet.element.old.element.Class</type>
  <coordinates>
    <x>20</x>
    <y>20</y>
    <w>240</w>
    <h>110</h>
  </coordinates>
  <panel_attributes>_instance: Object_
--
type="Type1"</panel_attributes>
  <additional_attributes/>
</element>
```
The result looks fine visually, but I get the warning "DEPRECATED ELEMENT WILL SOON BE REMOVED".
![image](https://github.com/user-attachments/assets/81ef1b82-4bd1-402c-8ba5-ed00dbde641d)

2. UMLClass
```
<element>
  <id>UMLClass</id>
  <coordinates>
    <x>20</x>
    <y>160</y>
    <w>750</w>
    <h>140</h>
  </coordinates>
  <panel_attributes>_instance: Object_
--
type="Type1"</panel_attributes>
  <additional_attributes/>
</element>
```
With this version, rendering fails completely:
![image](https://github.com/user-attachments/assets/2e0388f7-176e-4e1b-88ca-830225db2d2f)

**Comment by afdia** [comment]
I wouldn't use com.baselet.element.old.element.Class because those elements are deprecated and not usable in js-based versions of Umlet (umletino and vscode plugin)

UMLClass is the way to go, but type= is a command which means it's value will be interpreted and not printed like other lines

As a workaround, you have to make sure the line doesn't start with exactly "type="
e.g. a space at the beginning or any other slight modification like replacing = with : would be sufficient to print the line

**Comment by rtaupe** [comment]
Thank you for your response!
I'm aware of the workaround. It has the drawback that it changes the visual output, and I suggest to implement a feature that allows using the `type` attribute without a visual change. For example, starting a line with `'` to disable the command: e.g., coding `'type=Type1` but rendering it as `type=Type1`.

**Comment by afdia** [comment]
Maybe that could help, but we would have to show an example or otherwise nobody would find it
Escaping could be a potential feature, but I would use \. So if a line starts with \ it gets ignored (if there are more \ characters, they will be printed in case someone wants to write `\type=`

But on the other hand there are invisible UTF8 characters which basically do the same job already. E.g. start the line with https://invisible-characters.com/2064-INVISIBLE-PLUS.html or anything similar and it will look as if you used an escape character
It shouldn't cause problems because uxf files are UTF8 XML files, but I have not really tried it until now

**Comment by afdia** [comment]
Thanks for the info!
I will close the issue in the meantime, I'm not sure if we want to implement escaping in the future, but if it's the case, we will create a separate issue for that.
